#!/bin/bash
# Køyr denne i Terminal for å sletta alle dupliserte dikt-filer i Dikt Backup / Dikt Backup-1.
# Alle filene lista opp her er bit-identiske med sin motpart i Dikt/Draft/.
# Kjøring:   bash "slett-duplikatar-i-dikt-backup.sh"

cd "$(dirname "$0")" || exit 1

echo "Slettar 139 identiske filer ..."

rm -v -- "Dikt Backup/Draft/.DS_Store"
rm -v -- "Dikt Backup/Draft/ALTERNAT.md"
rm -v -- "Dikt Backup/Draft/ANGER.md"
rm -v -- "Dikt Backup/Draft/ARG.md"
rm -v -- "Dikt Backup/Draft/BARNDOMS.md"
rm -v -- "Dikt Backup/Draft/BON.md"
rm -v -- "Dikt Backup/Draft/BORD.md"
rm -v -- "Dikt Backup/Draft/DISSEKER.md"
rm -v -- "Dikt Backup/Draft/DJUPNEDE.md"
rm -v -- "Dikt Backup/Draft/DUVESLRA.md"
rm -v -- "Dikt Backup/Draft/EKKELT.md"
rm -v -- "Dikt Backup/Draft/EVITARE.md"
rm -v -- "Dikt Backup/Draft/Etterdønning.md"
rm -v -- "Dikt Backup/Draft/FAVORITT.md"
rm -v -- "Dikt Backup/Draft/FEIL.md"
rm -v -- "Dikt Backup/Draft/FRAMTID.md"
rm -v -- "Dikt Backup/Draft/FRITFALL.md"
rm -v -- "Dikt Backup/Draft/FURUPASK.md"
rm -v -- "Dikt Backup/Draft/GLEDAMI.md"
rm -v -- "Dikt Backup/Draft/HAPET.md"
rm -v -- "Dikt Backup/Draft/HAT.md"
rm -v -- "Dikt Backup/Draft/HM!.md"
rm -v -- "Dikt Backup/Draft/JANUARBI.md"
rm -v -- "Dikt Backup/Draft/Ja ja.md"
rm -v -- "Dikt Backup/Draft/KJAERLEI.md"
rm -v -- "Dikt Backup/Draft/KJEDELEG.md"
rm -v -- "Dikt Backup/Draft/KJENSLE.md"
rm -v -- "Dikt Backup/Draft/KJENSLE2.md"
rm -v -- "Dikt Backup/Draft/KVASEIED.md"
rm -v -- "Dikt Backup/Draft/LAVA.md"
rm -v -- "Dikt Backup/Draft/LENGT.md"
rm -v -- "Dikt Backup/Draft/LIV.md"
rm -v -- "Dikt Backup/Draft/Lese dikt.md"
rm -v -- "Dikt Backup/Draft/MANEN.md"
rm -v -- "Dikt Backup/Draft/MASEHOLM.md"
rm -v -- "Dikt Backup/Draft/MASESTUP.md"
rm -v -- "Dikt Backup/Draft/MISUNNIN.md"
rm -v -- "Dikt Backup/Draft/NAREINVE.md"
rm -v -- "Dikt Backup/Draft/NO.md"
rm -v -- "Dikt Backup/Draft/OMBAKS.md"
rm -v -- "Dikt Backup/Draft/PALEIT.md"
rm -v -- "Dikt Backup/Draft/PAREISE.md"
rm -v -- "Dikt Backup/Draft/PASKEAFT.md"
rm -v -- "Dikt Backup/Draft/PATETISK.md"
rm -v -- "Dikt Backup/Draft/PIONER.md"
rm -v -- "Dikt Backup/Draft/PUST.md"
rm -v -- "Dikt Backup/Draft/ROMANIA.md"
rm -v -- "Dikt Backup/Draft/Regnskyll-haiku.md"
rm -v -- "Dikt Backup/Draft/SAMANSVE.md"
rm -v -- "Dikt Backup/Draft/SKILSEGU.md"
rm -v -- "Dikt Backup/Draft/SKULEN.md"
rm -v -- "Dikt Backup/Draft/SLIK.md"
rm -v -- "Dikt Backup/Draft/SLIKKJEN.md"
rm -v -- "Dikt Backup/Draft/SLIKVIER.md"
rm -v -- "Dikt Backup/Draft/SOMORNA.md"
rm -v -- "Dikt Backup/Draft/STEMNING.md"
rm -v -- "Dikt Backup/Draft/STILLA.md"
rm -v -- "Dikt Backup/Draft/Sa Sisyfos.md"
rm -v -- "Dikt Backup/Draft/TAKKFORA.md"
rm -v -- "Dikt Backup/Draft/TILEINVE.md"
rm -v -- "Dikt Backup/Draft/TILMI.md"
rm -v -- "Dikt Backup/Draft/URO.md"
rm -v -- "Dikt Backup/Draft/USIKKER.md"
rm -v -- "Dikt Backup/Draft/VAL.md"
rm -v -- "Dikt Backup/Draft/VARTEIGE.md"
rm -v -- "Dikt Backup/Draft/VENSMEDD.md"
rm -v -- "Dikt Backup/Draft/VITO.md"
rm -v -- "Dikt Backup/Draft/YNSKJE.md"
rm -v -- "Dikt Backup/Draft/YNSKJE2.md"
rm -v -- "Dikt Backup-1/Draft/.DS_Store"
rm -v -- "Dikt Backup-1/Draft/ALTERNAT.md"
rm -v -- "Dikt Backup-1/Draft/ANGER.md"
rm -v -- "Dikt Backup-1/Draft/ARG.md"
rm -v -- "Dikt Backup-1/Draft/BARNDOMS.md"
rm -v -- "Dikt Backup-1/Draft/BON.md"
rm -v -- "Dikt Backup-1/Draft/BORD.md"
rm -v -- "Dikt Backup-1/Draft/DISSEKER.md"
rm -v -- "Dikt Backup-1/Draft/DJUPNEDE.md"
rm -v -- "Dikt Backup-1/Draft/DUVESLRA.md"
rm -v -- "Dikt Backup-1/Draft/EKKELT.md"
rm -v -- "Dikt Backup-1/Draft/EVITARE.md"
rm -v -- "Dikt Backup-1/Draft/Etterdønning.md"
rm -v -- "Dikt Backup-1/Draft/FAVORITT.md"
rm -v -- "Dikt Backup-1/Draft/FEIL.md"
rm -v -- "Dikt Backup-1/Draft/FRAMTID.md"
rm -v -- "Dikt Backup-1/Draft/FRITFALL.md"
rm -v -- "Dikt Backup-1/Draft/FURUPASK.md"
rm -v -- "Dikt Backup-1/Draft/GLEDAMI.md"
rm -v -- "Dikt Backup-1/Draft/HAPET.md"
rm -v -- "Dikt Backup-1/Draft/HAT.md"
rm -v -- "Dikt Backup-1/Draft/HM!.md"
rm -v -- "Dikt Backup-1/Draft/JANUARBI.md"
rm -v -- "Dikt Backup-1/Draft/Ja ja.md"
rm -v -- "Dikt Backup-1/Draft/KJAERLEI.md"
rm -v -- "Dikt Backup-1/Draft/KJEDELEG.md"
rm -v -- "Dikt Backup-1/Draft/KJENSLE.md"
rm -v -- "Dikt Backup-1/Draft/KJENSLE2.md"
rm -v -- "Dikt Backup-1/Draft/KVASEIED.md"
rm -v -- "Dikt Backup-1/Draft/LAVA.md"
rm -v -- "Dikt Backup-1/Draft/LENGT.md"
rm -v -- "Dikt Backup-1/Draft/LIV.md"
rm -v -- "Dikt Backup-1/Draft/Lese dikt.md"
rm -v -- "Dikt Backup-1/Draft/MANEN.md"
rm -v -- "Dikt Backup-1/Draft/MASEHOLM.md"
rm -v -- "Dikt Backup-1/Draft/MASESTUP.md"
rm -v -- "Dikt Backup-1/Draft/MISUNNIN.md"
rm -v -- "Dikt Backup-1/Draft/NAREINVE.md"
rm -v -- "Dikt Backup-1/Draft/NO.md"
rm -v -- "Dikt Backup-1/Draft/OMBAKS.md"
rm -v -- "Dikt Backup-1/Draft/PALEIT.md"
rm -v -- "Dikt Backup-1/Draft/PAREISE.md"
rm -v -- "Dikt Backup-1/Draft/PASKEAFT.md"
rm -v -- "Dikt Backup-1/Draft/PATETISK.md"
rm -v -- "Dikt Backup-1/Draft/PIONER.md"
rm -v -- "Dikt Backup-1/Draft/PUST.md"
rm -v -- "Dikt Backup-1/Draft/ROMANIA.md"
rm -v -- "Dikt Backup-1/Draft/Regnskyll-haiku.md"
rm -v -- "Dikt Backup-1/Draft/SAMANSVE.md"
rm -v -- "Dikt Backup-1/Draft/SKILSEGU.md"
rm -v -- "Dikt Backup-1/Draft/SKULEN.md"
rm -v -- "Dikt Backup-1/Draft/SKUTA.md"
rm -v -- "Dikt Backup-1/Draft/SLIK.md"
rm -v -- "Dikt Backup-1/Draft/SLIKKJEN.md"
rm -v -- "Dikt Backup-1/Draft/SLIKVIER.md"
rm -v -- "Dikt Backup-1/Draft/SOMORNA.md"
rm -v -- "Dikt Backup-1/Draft/STEMNING.md"
rm -v -- "Dikt Backup-1/Draft/STILLA.md"
rm -v -- "Dikt Backup-1/Draft/Sa Sisyfos.md"
rm -v -- "Dikt Backup-1/Draft/TAKKFORA.md"
rm -v -- "Dikt Backup-1/Draft/TILEINVE.md"
rm -v -- "Dikt Backup-1/Draft/TILMI.md"
rm -v -- "Dikt Backup-1/Draft/URO.md"
rm -v -- "Dikt Backup-1/Draft/USIKKER.md"
rm -v -- "Dikt Backup-1/Draft/VAL.md"
rm -v -- "Dikt Backup-1/Draft/VARTEIGE.md"
rm -v -- "Dikt Backup-1/Draft/VENSMEDD.md"
rm -v -- "Dikt Backup-1/Draft/VITO.md"
rm -v -- "Dikt Backup-1/Draft/YNSKJE.md"
rm -v -- "Dikt Backup-1/Draft/YNSKJE2.md"

echo "Ferdig. Desse filene var ULIKE og vart IKKJE sletta:"
echo "  - Dikt Backup/Draft/SKUTA.md"
